version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    volumes:
      - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    volumes:
      - "./logstash/pipeline:/usr/share/logstash/pipeline:ro"
    ports:
      - "5000:5000/tcp"
      - "5044:5044/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elk
  
  filebeat:
    user: root
    image: docker.elastic.co/beats/filebeat:7.12.0
    volumes:
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - elk
  
  api:
    build: .
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ".:/app"
    networks:
      - elk

volumes:
  esdata1:
    driver: local

networks:
  elk:
    driver: bridge
